### ISSUE TITLE
Fix key error

### ISSUE THREAD

**Issue by johno** [c8r/markdown#75]
In the renderer we should be adding a key prop, we currently aren't resulting in the following error:

```
Warning: Each child in an array or iterator should have a unique "key" prop
```

**Comment by ericclemmons** [comment]
Was this fixed? I just saw the same warning & trying to figure out the best solution.

**Comment by johno** [comment]
It _should_ be fixed in MDX. Is there a component that's being used which might be causing the key error? If you can create a reproduction I'd be happy to reopen and dig in.
