### ISSUE TITLE
Adds babel + yaml parser to the bundle

### ISSUE THREAD

**Issue by timneutkens** [c8r/markdown#80]
And a few other modules 😅 
<img width="370" alt="screen shot 2018-03-07 at 09 03 51" src="https://user-images.githubusercontent.com/6324199/37080427-86b69626-21e6-11e8-8c67-436f20029e53.png">

**Comment by timneutkens** [comment]
Looks like it's caused by the `<Markdown>` component doing remark on the fly, instead of at compile time.

**Comment by johno** [comment]
Fixed in `0.3.0`.
